### ISSUE TITLE
Cannot read config file

### ISSUE THREAD

**Issue by patrykk21** [mantoni/eslint_d.js#293]
## Introduction

I'm using nvim with `none-ls` LSP installation and since the upgrade of the project's node version from 18.16 to 18.17.1 I've started having failures for eslint_d on all files.

I also opened a discussion [here](https://github.com/nvimtools/none-ls.nvim/discussions/166)

## Trace

```
[TRACE Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/rpc.lua:131: received LSP notification for method textDocument/didChange
[TRACE Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS
[DEBUG Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:329: spawning command "eslint_d" at /Users/vigenerr/Work/Projects/mkt-bi-link-building-tool with args { "-f", "json", "--stdin", "--stdin-filename", "/Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/lib/jobs/SyncSkillsJob/SyncSkillsJob.test.ts" }
[TRACE Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:207: error output: Error: Cannot read config file: /Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/node_modules/eslint-config-next/index.js
Error: Cannot find module '/Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/node_modules/eslint-config-next/node_modules/eslint-import-resolver-typescript/lib/index.cjs'
Referenced from: /Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/.eslintrc.json

[TRACE Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/helpers/generator_factory.lua:208: output: nil
[TRACE Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE Wed Jul 24 14:04:53 2024] /Users/vigenerr/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/diagnostics.lua:182: { {
    col = 0,
    end_col = 0,
    end_lnum = 1,
    lnum = 0,
    message = "Error: Cannot read config file: /Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/node_modules/eslint-config-next/index.js\nError: Cannot find module '/Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/node_modules/eslint-config-next/node_modules/eslint-import-resolver-typescript/lib/index.cjs'\nReferenced from: /Users/vigenerr/Work/Projects/mkt-bi-link-building-tool/.eslintrc.json\n",
```
    
## What do I expect from this issue?

To receive pointers and guidance on how to solve this. Eslint is a very important part of our project and it makes my life much harder not having it

## Version

13.1.2

**Comment by mantoni** [comment]
Are you sure this is an issue with `eslint_d` and not with `eslint`?

**Comment by patrykk21** [comment]
@mantoni thank you for your assistance.

I'm not. How would you suggest me testing this?

**Comment by mantoni** [comment]
Well, you could remove the `eslint_d` config and see whether that fixes it. If it doesn't, it's something else.

**Comment by mantoni** [comment]
I think this is your issue: https://github.com/MunifTanjim/eslint.nvim/issues/6

**Comment by mantoni** [comment]
This is probably obsolete with the new major `v14.0.0` (see #294). Should you're still having problems, please open a new issue.

**Comment by patrykk21** [comment]
@mantoni updating to 14.0.1 solved my issue.

Thank you
